### ISSUE TITLE
Error: Cannot find module '@chainlink/functions-toolkit'

### ISSUE THREAD

**Issue by adam-lokicode** [PatrickAlphaC/rwa-creator#10]
Hi I was listening to the lecture and found when I ran the Make command I encountered the following error

Error: Cannot find module '@chainlink/functions-toolkit'

I have tried various versions of NPM and a few other things but still couldn't get it to work.  

Any ideas?

**Comment by PatrickAlphaC** [comment]
Hmm... I'm unable to reproduce. Could you please copy paste the exact steps you took to get that error? Starting from `git clone https://github.com/PatrickAlphaC/rwa-creator`?

Thanks!

**Comment by PatrickAlphaC** [comment]
Closing, feel free to open if you need.
