### ISSUE TITLE
please add .env.expample to files

### ISSUE THREAD

**Issue by saremeskandary** [PatrickAlphaC/rwa-creator#11]
hi. I tried to install it with make but I got lots of errors. I realize that there is no .env and I need to add it. but I didn't know what;s the environment variables are

**Comment by PatrickAlphaC** [comment]
Can you give exactly "what" command you ran to get exactly "what" error? That way I can help address most effectively.

**Comment by saremeskandary** [comment]
I got 2 error that I fixed it.
error 1 related to evm version that I fixed it by commenting the `evm_version = "cancun"` in _foundry.toml_ .
```
failed to extract foundry config:
foundry config error: Unknown evm version: cancun for setting `evm_version`
```

second one is Makefile `npm run simulate`
```
> simulate
> source .env && node ./functions/simulators/alpacaMintSimulator.js

sh: 1: source: not found
```

it would be nice to add `.env.example` to the project.
I think the content would be this.
```
PRIVATE_KEY=
SEPOLIA_RPC_URL=
ALPACA_KEY=
ALPACA_SECRET=
```

**Comment by PatrickAlphaC** [comment]
Good idea. Created!
