### ISSUE TITLE
Issue with a checker inside `sendMintRequest` function

### ISSUE THREAD

**Issue by Jaseempk** [PatrickAlphaC/rwa-creator#13]
https://github.com/PatrickAlphaC/rwa-creator/blob/35af5e0a0ebee5f330ddabb5cc516e1a1487fa86/src/dTSLA.sol#L137

`s_portfolioBalance` is updated only in the `_mintFulFillRequest` function which is called inside `fulfillRequest` function.
So If I'm not wrong when we initially call `sendMintRequest` function this `s_portfolioBalance` will be zero right, then this function call is always gonna revert right?
Correct me If I'm wrong.

**Comment by PatrickAlphaC** [comment]
You're right! We should initialize calling this func

**Comment by Jaseempk** [comment]
what would be the better approach for this?
Is it optimal to just initialise the value of `s_portfolioBalance` by calling a function in the constructor like this?
```
    function initializePortfolioBalance(bytes memory response) internal {
        s_portfolioBalance = uint256(bytes32(response));
    }

**Comment by PatrickAlphaC** [comment]
Hmm... Yes! Have an initializer with a balance would be great.

**Comment by Jaseempk** [comment]
yep got it thanks
