### ISSUE TITLE
ChainLink Functions Error

### ISSUE THREAD

**Issue by adam-lokicode** [PatrickAlphaC/rwa-creator#14]
Hi Patrick,

I am getting the following error from Chainlink:

![Screenshot 2024-06-23 at 11 42 54 PM](https://github.com/PatrickAlphaC/rwa-creator/assets/132405074/d070f8c1-40b0-40eb-8c5b-30ab6ff5227c)

`failed to fetch DONHosted secrets: not found`

I didn't really change anything from the code that is hosted here but where could I start looking to resolve this issue? 

Thanks

**Comment by PatrickAlphaC** [comment]
Did you upload your secrets?

https://github.com/PatrickAlphaC/rwa-creator/blob/main/functions/uploadSecrets.js

**Comment by adam-lokicode** [comment]
Yes I did, please see my successful upload of secrets from the terminal 

<img width="1180" alt="Screenshot 2024-06-24 at 11 52 42 PM" src="https://github.com/PatrickAlphaC/rwa-creator/assets/132405074/fa43e511-7f4b-4029-9f43-d95bca487c2c">

https://github.com/adam-lokicode/rwa-creator/blob/main/functions/uploadSecrets.js

**Comment by PatrickAlphaC** [comment]
Hmm... You'll need to add the `version` to your source, did you do that as well? 

https://github.com/PatrickAlphaC/rwa-creator/blob/35af5e0a0ebee5f330ddabb5cc516e1a1487fa86/script/DeployDTsla.s.sol#L28

You'd need to update your `HelperConfig.s.sol` with the correct secret version.

**Comment by adam-lokicode** [comment]
Oh I figured this out so I think we are good for now, thanks
