### ISSUE TITLE
Reopening The Following Issue

### ISSUE THREAD

**Issue by adam-lokicode** [PatrickAlphaC/rwa-creator#16]
https://github.com/PatrickAlphaC/rwa-creator/issues/15

I removed the access controls and I still run into issues.  I still need to local testing but I don't think it would cause the issues described since most of my code is the same, please see here: 

[https://github.com/adam-lokicode/rwa-creator](https://github.com/adam-lokicode/rwa-creator)

**Comment by PatrickAlphaC** [comment]
Hello, 

This is known as a "debug me" issue, and it's not something that makes it easy for me to answer. You can reference our [how to ask a question](https://github.com/Cyfrin/foundry-full-course-cu/blob/main/how-to-ask-a-question.md) file for more information on making effective issues. 

Can you minimize the problem that you're running into here? Thanks.

**Comment by adam-lokicode** [comment]
Ok let me take a closer look, don't mean to pass my problems onto yours.
