### ISSUE TITLE
WBTC isn't directly backed asset?

### ISSUE THREAD

**Issue by PrathmeshRanjan** [PatrickAlphaC/rwa-creator#6]
WBTC is mentioned in the category of on-chain asset, on-chain collateral & indirect backing (synthetic) but WBTC is an ERC-20 token backed 1:1 with BTC which makes it a directly backed asset according to me. Is this correct or am I missing out on something?

**Comment by PatrickAlphaC** [comment]
Where do we say that?

https://github.com/PatrickAlphaC/rwa-creator?tab=readme-ov-file#currently-live-examples-of-tokenized-rwas

It looks like we said it's "Fully Reserved" which means "Directly backed"
