### ISSUE TITLE
Review the 'forge install' section in the Makefile

### ISSUE THREAD

**Issue by hex-aragon** [PatrickAlphaC/rwa-creator#9]
Hello, I'm listening to the Chainlink Hackathon lecture and I think there is something missing in the process of building with the make command. 

I think I missed the part of installing ccip contract in the before and after as follows, so I get an error when executing the make command, so please check it~~.

Makefile line 15

```
before :
install :; forge install cyfrin/foundry-devops --no-commit && forge install smartcontractkit/chainlink-brownie-contracts@0.8.0 --no-commit && forge install foundry-rs/forge-std --no-commit && forge install openzeppelin/openzeppelin-contracts --no-commit

after : 
install :; forge install cyfrin/foundry-devops --no-commit && forge install smartcontractkit/chainlink-brownie-contracts@0.8.0 --no-commit && forge install foundry-rs/forge-std --no-commit && forge install openzeppelin/openzeppelin-contracts --no-commit && forge install cyfrin/ccip-contracts@1.4.0 --no-commit

```

I modified the file like after and make finished fine.

Please check it out 

Translated with DeepL.com (free version)

**Comment by PatrickAlphaC** [comment]
You're right!

Fixed

https://github.com/PatrickAlphaC/rwa-creator/commit/7c5fcc4363dc90ae7df7dfee7f18dddb8e8f58f1
